// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go.uber.org/zap"
	"official-account-service/internal/application"
	"official-account-service/internal/interfaces/http"
)

// Injectors from wire.go:

func buildHTTPDependencies(logger *zap.Logger, authorization *application.AuthorizationService, accounts *application.AccountService, articles *application.ArticleService, materials *application.MaterialService, publishes *application.PublishService, tokens *application.TokenService, callbacks *application.CallbackService, taskQueues *application.TaskQueueService) http.Dependencies {
	dashboardService := application.NewDashboardService(accounts, articles, publishes)
	dependencies := provideHTTPDependencies(logger, authorization, accounts, articles, materials, publishes, tokens, callbacks, taskQueues, dashboardService)
	return dependencies
}
